dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  development:
      keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
      fee: 1000_000_000_000_000_00
  rinkeby: 
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 1000_000_000_000_000_00